<template>
  <AppTable
    hide-page-title
    wide-first-column
    title="Movimientos"
    :headers="headers"
    :row-options="[]"
    :filters="tableFilters"
    :items="items"
    :chip-columns="chipColumns"
    :loading="stockStore.movementsLoading"
    :page="currentPage"
    :items-per-page="itemsPerPage"
    :total-items="totalItems"
    :show-create-button="false"
    :show-export-button="false"
    :show-search="false"
    :empty-title="emptyTitle"
    :empty-text="emptyText"
    @update:pagination="handlePagination"
    @handle-update-filters="handleUpdateFilters"
  >
    <template #item.quantity="{ item }">
      <span :class="item.quantity < 0 ? 'text-error' : 'text-success'" class="font-weight-medium">
        {{ item.quantityLabel }}
      </span>
    </template>

    <template #item.purchaseOrderNumber="{ item }">
      <NuxtLink
        v-if="item.purchaseOrderId"
        :to="`/app/purchase-orders/${item.purchaseOrderId}`"
        class="text-primary font-weight-medium"
      >
        {{ item.purchaseOrderNumber }}
      </NuxtLink>
      <span v-else class="text-medium-emphasis">—</span>
    </template>
  </AppTable>
</template>

<script setup lang="ts">
import type { FilterOption, TableChipColumn, TableHeader } from "~/interfaces/tableInterfaces"
import type { MovementType } from "~/interfaces/stockInterfaces"
import { MOVEMENT_TYPE_COLORS, MOVEMENT_TYPE_OPTIONS, getMovementTypeLabel } from "~/interfaces/stockInterfaces"
import { useStockStore, useWarehousesStore } from "~/store"
import { formatDateOnly, formatDateTime, formatMoney, formatQuantity } from "~/helpers/formatHelpers"

/**
 * Stock movement history (kardex), in three flavours:
 *  - general (default): every movement, with warehouse / type filters; optionally for one product
 *    (`productId`, where the product column is redundant: `hideProductColumn`).
 *  - one purchase order (`purchaseOrderId`): just what was received against it. A single order has one warehouse
 *    and only receipts, so there are no filters and the columns that don't apply are dropped.
 *  - all receipts (`receiptsOnly`): goods received across all orders, with supplier and order.
 */
const props = defineProps<{
  productId?: number | null
  /** Only the movements generated by this purchase order (its receipts). */
  purchaseOrderId?: number | null
  /** Only goods received against purchase orders (movement type PURCHASE), across all orders. */
  receiptsOnly?: boolean
  hideProductColumn?: boolean
}>()

const stockStore = useStockStore()
const warehousesStore = useWarehousesStore()

const currentPage = ref(1)
const itemsPerPage = ref(10)
const activeFilters = reactive<{ warehouseId?: number; type?: MovementType }>({})

const isOrderView = computed(() => !!props.purchaseOrderId)
const isReceiptsView = computed(() => !!props.receiptsOnly && !isOrderView.value)

const headers = computed<TableHeader[]>(() => {
  if (isOrderView.value) {
    return [
      { title: "Fecha", key: "createdAtLabel" },
      { title: "Producto", key: "productLabel" },
      { title: "Lote / vence", key: "lotLabel" },
      { title: "Recibido", key: "quantity" },
      { title: "Costo unit.", key: "unitCostLabel" },
      { title: "Recibió", key: "userName" },
      { title: "Notas", key: "notes" },
    ]
  }

  if (isReceiptsView.value) {
    return [
      { title: "Fecha", key: "createdAtLabel" },
      { title: "Orden", key: "purchaseOrderNumber" },
      { title: "Proveedor", key: "supplierName" },
      { title: "Producto", key: "productLabel" },
      { title: "Almacén", key: "warehouseName" },
      { title: "Lote / vence", key: "lotLabel" },
      { title: "Recibido", key: "quantity" },
      { title: "Costo unit.", key: "unitCostLabel" },
      { title: "Recibió", key: "userName" },
    ]
  }

  return [
    { title: "Fecha", key: "createdAtLabel" },
    { title: "Tipo", key: "typeLabel" },
    ...(props.hideProductColumn ? [] : [{ title: "Producto", key: "productLabel" }]),
    { title: "Almacén", key: "warehouseName" },
    { title: "Lote / vence", key: "lotLabel" },
    { title: "Cantidad", key: "quantity" },
    { title: "Saldo", key: "balanceLabel" },
    { title: "Costo unit.", key: "unitCostLabel" },
    { title: "Usuario", key: "userName" },
    { title: "Referencia", key: "purchaseOrderNumber" },
    { title: "Notas", key: "notes" },
  ]
})

const chipColumns: TableChipColumn[] = [
  { key: "typeLabel", color: (item) => MOVEMENT_TYPE_COLORS[item.type as MovementType] ?? "default" },
]

const tableFilters = computed<FilterOption[]>(() => {
  // One order = one warehouse and only receipts: filtering would be noise.
  if (isOrderView.value) return []

  const warehouse: FilterOption = {
    type: "select",
    label: "Almacén",
    key: "warehouseId",
    items: warehousesStore.options.map((w) => ({ title: w.name, value: w.id })),
  }

  // Receipts are already only one type, so the type filter would be pointless there.
  if (isReceiptsView.value) return [warehouse]

  return [warehouse, { type: "select", label: "Tipo", key: "type", items: MOVEMENT_TYPE_OPTIONS }]
})

const emptyTitle = computed(() =>
  isOrderView.value || isReceiptsView.value ? "Aún no hay recepciones" : "Sin resultados"
)

const emptyText = computed(() => {
  if (isOrderView.value) return "Cuando recibas mercadería de esta orden, aparecerá aquí."
  if (isReceiptsView.value) return "La mercadería que recibas de tus órdenes de compra aparecerá aquí."
  return "No se encontraron registros con los filtros actuales"
})

const items = computed(() =>
  (stockStore.movements?.content ?? []).map((movement) => {
    // The unit isn't part of the movement payload, so quantities are shown without it.
    const sign = movement.quantity > 0 ? "+" : ""

    return {
      ...movement,
      createdAtLabel: formatDateTime(movement.createdAt),
      typeLabel: getMovementTypeLabel(movement.type),
      productLabel: movement.productSku
        ? `${movement.productSku} — ${movement.productName}`
        : movement.productName ?? "—",
      lotLabel: movement.expiryDate
        ? `${movement.lotNumber ? `${movement.lotNumber} · ` : ""}${formatDateOnly(movement.expiryDate)}`
        : "—",
      quantityLabel: `${sign}${formatQuantity(movement.quantity)}`,
      balanceLabel: formatQuantity(movement.balanceAfter),
      unitCostLabel: formatMoney(movement.unitCost),
    }
  })
)

const totalItems = computed(() => stockStore.movements?.totalElements ?? 0)

const fetchMovements = () =>
  stockStore.fetchMovements({
    page: currentPage.value - 1,
    size: itemsPerPage.value,
    productId: props.productId ?? undefined,
    purchaseOrderId: props.purchaseOrderId ?? undefined,
    warehouseId: activeFilters.warehouseId,
    type: isReceiptsView.value ? "PURCHASE" : activeFilters.type,
  })

const handleUpdateFilters = (values: Record<string, any>) => {
  activeFilters.warehouseId = values.warehouseId ?? undefined
  activeFilters.type = values.type ?? undefined
  currentPage.value = 1
  fetchMovements()
}

const handlePagination = async ({ page, itemsPerPage: size }: { page: number; itemsPerPage: number }) => {
  currentPage.value = page
  itemsPerPage.value = size
  await fetchMovements()
}

// A different product / order (or clearing it) restarts from the first page.
watch(
  () => [props.productId, props.purchaseOrderId],
  () => {
    currentPage.value = 1
    fetchMovements()
  }
)

onMounted(async () => {
  // Start clean: the store keeps the last list, which may belong to another product or order.
  stockStore.clearMovements()
  warehousesStore.fetchOptions()

  // The table normally triggers the first load through its pagination event; this is only a fallback.
  await nextTick()
  if (!stockStore.movements && !stockStore.movementsLoading) {
    fetchMovements()
  }
})
</script>
